### PR TITLE
Add metrics package

### PR DESCRIPTION
**Pull request by bkeepers**
This adds the [probot-metrics](https://github.com/probot/metrics) package to start tracking some basic metrics.

- [ ] Fix plugin loading so `probot-*` plugins are automatically loaded, even if a local script like `./index.js` is loaded. 
- [ ] Or: It's not really ideal to have this as a dependency on every single plugin, so explore if there's a better way to declare dependencies like this. Options:
  1. Add `probot-metrics` dependency on probot itself, so it's always available for all plugins, and is  a noop if the `GOOGLE_ANALYTICS_ID` environment variable is not set
  2. Is there a way to declare production-only dependencies? I'm guessing it would require defining a new `package.json` that has a dependency on both plugins
- [ ] Release `probot-metrics` plugin

@gr2m I'd love your thoughts on this

### CODE REVIEW

**Comment by gr2m** [comment]
> `probot-*` plugins are automatically loaded

I’m not sure if that’s a good idea at this point. I think I’d keep everything very explicit, have people programatically load plugins in their `./index.js` file, it’s really not that complicated. And then people can load plugins conditionally if any logic they need.

I understand you want things to make simpler, but too much magic especially at the early stage of where probot is today, I’d rather keep things clear and explicit. At this stage, I’d say it’s okay to require little bit of JS skills to work with probot, too. And it’s all following the node/npm conventions anyway

> @gr2m I'd love your thoughts on this

I’ll need some more time to review `probot-metrics`, I can’t give you an estimate right now. Happy to do a quick call to get up-to-speed with all things probot :)

**Comment by gr2m** [comment]
Okay I understand what `probot-metrics` is doing from looking at its code.

I’d keep it a separate plugin. Adding it to a probot app is easy enough. I wouldn’t make it a dependency of `probot` itself

**Comment by bkeepers** [comment]
>> `probot-*` plugins are automatically loaded
>
> I’m not sure if that’s a good idea at this point. I think I’d keep everything very explicit…

It actually [already autoloads `probot-*` if no plugin is explicitly loaded](https://github.com/probot/probot/blob/f0b3f4993faa706d7eed67de2aa621e594021538/bin/probot-run.js#L64-L69). This was originally added to make it easy to creating a deployment that [combines multiple plugins](https://github.com/probot/probot/blob/master/docs/deployment.md#combining-plugins). In practice, I haven't used this at all, so I could see removing it.

**Comment by bkeepers** [comment]
Giving up on this for now.

**Pull request closed without merging**
