### PR TITLE
Change default label from 'wontfix' to 'stale'

### LINKED ISSUE #109: Change default label from "wontfix" to "stale"
In my understanding, `wontfix` has history and meaning and contextual baggage. In other contexts, it's used with intention after [thoughtful] consideration of a maintainer. I don't feel a bot should be tagging things `wontfix`, because it conveys more than the bot can know (or should know, unless we as maintainers of this bot are imposing an intended use).

I'm reading elsewhere that the desire is not to close issues, but to
- **mark issues** as less relevant and
- **communicate that it needs attention** to escape that mark

then can we default to something more neutral? I would suggest `stale`. Maintainers can filter on that (even if they're not using the "close" functionality, and get a sense of the "actual" valuable tickets are in their midst :)

### PR DESCRIPTION
**Pull request by waldyrious**
Fixes #109 and #74.

Support for this change has been expressed by @patcon, @christianbundy, @sindresorhus, @paulmelnikow, @dwijnand, @darthmaim and @max-sixty in the issues linked above, and likely others who may have subscribed to them but haven't added comments or reactions to the discussion threads.

-----
[View rendered README.md](https://github.com/waldyrious/stale/blob/change-default-stale-label/README.md)

### CODE REVIEW

**Comment by patcon** [comment]
Thanks @waldyrious!

Alternative to the concern that `stale` isn't a default label: if the label doesn't exist, drop the message, and append a note to administrator that they'll need to create the `stale` label or set `staleLabel` to an existing label in order for functionality to work properly.

Not advocating that this necessarily needs to be within scope of this PR though

**Comment by christianbundy** [comment]
> Alternative to the concern that stale isn't a default label: if the label doesn't exist, drop the message, and append a note to administrator that they'll need to create the `stale` label or set `staleLabel` to an existing label in order for functionality to work properly.

Is this true? I've never had to create the stale label, it gets created automatically when the label is added to an issue.

**Comment by patcon** [comment]
Oooo I didn't realize. Maybe I'm remembering old behaviour that was referenced in past issues that spoke against changing the default. But seems its been auto-created for at least 3 years

https://github.com/probot/stale/blame/71669525fd170d53194a4751fe967dc9c26a8a92/lib/stale.js#L204-L211

**Comment by christianbundy** [comment]
:/

**Comment by waldyrious** [comment]
🤦

**Comment by christianbundy** [comment]
this is fun

**Comment by JamesMGreene** [comment]
As a GitHub App with many existing installations, Stale's major risk in changing this default is that it will negatively impact existing repository installations that chose not to explicitly set the default label because they were happy with `wontfix`.

By changing the default here, those repository installations will be forced to either explicitly set that label now in their configuration now (:warning: without any warning, my you :warning:) or else future runs of Stale will creating a separate `stale` label and the behavior will become fractured as it won't honor `wontfix` labels that were applied to stale issues. 😕 

Unfortunately, GitHub Apps don't have the luxury of opt-in versioning like, say, NPM package consumption or GitHub Action consumption does. If they did, I would suggest we just make this a breaking change (major version increment) per SemVer and ship it. However, without that capability, my personal inclination is to decline this change. 🤷🏻‍♂️ 

@tcbyrd @JasonEtco @hiimbex Thoughts?

**Comment by patcon** [comment]
Thanks for engaging, @JamesMGreene :)

For a default that needed to change and folks agreed it was important, how would that happen? Is this what versioned config is for? Is there any precedent for allowing GitHub Apps to change defaults without pain, even when they're big.

Will admit (without judgement) that it feels a bit frustrating to hear "we're too big to do this now" after 3 years. ❤️ 

As I've said elsewhere, being able to change defaults feels like a challenge worth engaging with, at least when we live imperfectly in a world where we'll almost surely make mistakes in deciding those defaults (not saying this is the case here).

Thanks!

**Comment by waldyrious** [comment]
@JamesMGreene if a significant portion of this app's users did prefer the current usage, I think it would be reasonable to expect at least some of that sentiment to have been manifested after almost 3 years since #74 was created — either there, in #109, or in this PR. Instead, what can be seen is overwhelming support for this change, both in the comments and in the reactions.

If anything, one could argue that the current behavior is _more_ disruptive, since the bot removes the `wontfix` label when an issue has activity, which is problematic for the cases where the label was actually applied for its intended purpose, i.e. as a final state for an issue. That has been reported as #294.

**Comment by JasonEtco** [comment]
I think @JamesMGreene said it right here. Part of the issue is that GitHub Apps don't have versioning, part of it is that introducing this kind of change is going to mess with a bunch of peoples' existing installations and require help from us.

> Will admit (without judgement) that it feels a bit frustrating to hear "we're too big to do this now" after 3 years. 

I get why this is frustrating. Probot, especially Stale, has seen folks come and go, and its now in a state where we'd rather not mess with it. I realize that doesn't sound great, but its the reality. It's in use by enough big orgs/repos that changing the behavior is going to cause a bunch of bugs and support requests that we simply can't deal with.

The original authors have left, there are better alternatives now (see [actions/stale](https://github.com/actions/stale), and accepting significant changes means a big risk from the people (myself and the other folks mentioned above) that we'll have to put out fires for the users who have Stale installed.

> Instead, what can be seen is overwhelming support for this change, both in the comments and in the reactions.

I don't mean to nitpick, but this isn't overwhelming support - the large majority of Stale users are fine with the default, or at least haven't told us otherwise. That's where configuration is important, and changing the default label shouldn't be an issue. 

I'd also recommend sharing these concerns in [actions/stale](https://github.com/actions/stale), a GitHub Actions version of Stale. They've chosen to set the default label as `Stale`.

**Comment by JamesMGreene** [comment]
#294 can be dealt with in a different and non-breaking fashion. Left a suggestion in that issue at https://github.com/probot/stale/issues/294#issuecomment-675743059

**Comment by christianbundy** [comment]
:roll_eyes:

**Comment by JamesMGreene** [comment]
Apologies to all of you who have expressed interest in this change but, alas, we are going to close it as `wontfix` (and yes, I absolutely see the irony) based on the discussion included here (namely, the unavoidable negative impact to existing installations).

I fully empathize with you all on this one. 💔  I agree that `stale` is a more practical default value to use but based on the historical configuration and large installation count, I also concur that it is best not to change that now. 😕  

Also, my apologies that we did not close this sooner. 🙇🏻‍♂️

**Pull request closed without merging**
