### PR TITLE
Add ability to ignore issues with an assignee

### PR DESCRIPTION
**Pull request by christianbundy**
This gives maintainers the ability to assign themselves (or someone else) to keep an issue being marked as stale. My hope is that this will let individual maintainers take responsibility for issues which would otherwise be marked as stale. Heavily influenced by #88. Thanks for your work on this project!

-----
[View rendered README.md](https://github.com/christianbundy/stale/blob/exempt-assignees/README.md)

### CODE REVIEW

**Comment by christianbundy** [comment]
Thanks for the quick review @pchaigno! I've just added some tests, please let me know if there's any other test coverage you think would be appropriate. Happy to hear Linguist is using Stale, I've always had great experiences on that repo. :heart:

**Comment by pchaigno** [comment]
> I've always had great experiences on that repo

Great to hear!

**Comment by christianbundy** [comment]
Anything I can do to help this along? I'd really love to use this to keep some issues from becoming stale.

**Comment by christianbundy** [comment]
Sorry to bother you, but I'd really love to get feedback on this before stale[bot] marks everything as stale again. Please let me know if you need any information or changes from me. Thanks! :sparkles: 

cc: @pchaigno @hiimbex @bkeepers

**Comment by christianbundy** [comment]
Thanks a lot! Looking forward to using this.

**Comment by pchaigno** [comment]
I'm noticing this a bit late, but shouldn't it be `exemptAssigned` rather than `exemptAssginees`?

**Comment by christianbundy** [comment]
@pchaigno 

Feel free to change it if you'd like, I followed the pattern of `exemptMilestones` and `exemptProjects` when I chose `exemptAssignees`, but I don't have any strong feelings either way. :+1:

**Comment by pchaigno** [comment]
@JasonEtco When will this take effect on GitHub? If it's not in effect yet, I'll open a pull request.

**Comment by christianbundy** [comment]
@pchaigno It's already working, check out [my test](https://github.com/christianbundy/stale-test/issues)!

**Pull request merged**
