### PR TITLE
README: Adjust expectations for initial results

### PR DESCRIPTION
**Pull request by tyll**
The `How long will it take?` section tells to expect results within 24 hours. Use this time window in the Usage as well.

-----
[View rendered README.md](https://github.com/tyll/stale/blob/patch-1/README.md)

### CODE REVIEW

**Comment by tyll** [comment]
@JamesMGreene can you maybe merge this? It is trivial.

**Comment by JamesMGreene** [comment]
This feels correct but I don't have the intel to confirm it right now. 🤔 

If nothing else, 1 hour is within 24 hours so it would at least still be accurate. 😅

**Comment by tyll** [comment]
> This feels correct but I don't have the intel to confirm it right now. 
> 
> If nothing else, 1 hour is within 24 hours so it would at least still be accurate.

It got the information on Slack, I believe. But I cannot find any reference to Slack or any other support channel currently.

**Comment by JamesMGreene** [comment]
@tyll Thank you for your contribution, and apologies for the delay in getting it merged. 🙇🏻‍♂️

**Pull request merged**
