### PR TITLE
Merge no response behavior into probot-stale

### PR DESCRIPTION
**Pull request by lee-dohm**
@bkeepers per our previous discussion

### TODO

* [ ] Finish writing tests for `Stale`
* [ ] Write tests for `NoResponse`
* [ ] Manual test to ensure everything still works
* [ ] Design sign-off from @bkeepers

### CODE REVIEW

**Comment by bkeepers** [comment]
Thanks, @lee-dohm, I think this a really helpful feature.

I'd love to explore how to make this plugin a little more generic, so instead of having separate implementations for stale and no-response, it can be more configuration-driven. It looks like both implementations basically do some for of this:

1. search for issues/PRs that match some condition and label, comment on, or close those issues
2. when something changes on an issue/PR, remove certain labels

For the first part, here's one idea for what the config might look like.

```yml
# No response
- age: 14
  withLabel: more-information-needed
  comment:
      This issue has been automatically closed because there has been no response
      to our request for more information from the original author. With only the
      information that is currently in the issue, we don't have enough information
      to take action. Please reach out if you have or find the answers we need so
      that we can investigate further.
  close: true # don't love this, but can't think of a better way to do it

# stale
- age: 60
  withoutLabel: pinned, security
  comment: >
    This issue has been automatically marked as stale because it has not had
    recent activity. It will be closed if no further activity occurs. Thank
    you for your contributions.
  addLabel: stale

# really stale
- age: 7
  withLabel: stale
  close: true
```

What do you think about that direction?

**Comment by lee-dohm** [comment]
The problem I have with unifying these two state machines is that `age` is marked between different start and end points for the two behaviors.

* No Response
    * **Start:** When `withLabel` is added
    * **End:** When the original author comments
* Stale
    * **Start:** When the last comment is posted
    * **End:** When _any_ comment is posted (so long as it happens before it is closed)

While I agree that conceptually they are similar and should share code therefore should probably be included in the same plugin, the fact that they are mostly different state machines suggests that the behaviors themselves should be kept separate.

**Comment by bkeepers** [comment]
> The problem I have with unifying these two state machines is that `age` is marked between different start and end points for the two behaviors.

Ahh, sorry, I missed that in my initial read through of the code.

Does it happen often where the `more-information-needed` label is added and someone _besides_ the original author comments? And if so, do you want to auto close it if someone is still giving feedback?

I'm just curious if you could get by with the no response behavior acting the same as stale in most cases.

**Comment by MikeMcQuaid** [comment]
> Does it happen often where the more-information-needed label is added and someone besides the original author comments? And if so, do you want to auto close it if someone is still giving feedback?

In Homebrew's case: yes and yes. We're specifically looking from feedback from the original PR/issue author and other maintainers may still chip in and talk among themselves before that point.

**Comment by MikeMcQuaid** [comment]
@lee-dohm Would love to help get this in as it's something Homebrew would like (we have two separate bots doing this currently and sometimes they "fight").

**Comment by lee-dohm** [comment]
> Does it happen often where the more-information-needed label is added and someone besides the original author comments? And if so, do you want to auto close it if someone is still giving feedback?

@bkeepers Yes, it does happen often and, yes, at least for Atom we still want to auto close it if someone other than the original author is giving feedback because in almost all cases people glomming on to someone else's issue have a different root cause. Getting them to open a new issue allows us to get all the information we need on the new person's problem to diagnose the issue.

@MikeMcQuaid I'll take a look at getting this updated later today and then let you know what the status is and point out places where you could help, if needed. Thanks very much for the offer! :bow:

**Comment by lee-dohm** [comment]
I merged the latest `master` in and added todos up above.

@bkeepers Given the discussion above, do you still think it is a good idea to merge the two behaviors into the Stale plugin?

**Comment by MikeMcQuaid** [comment]
> @bkeepers Given the discussion above, do you still think it is a good idea to merge the two behaviors into the Stale plugin?

My $0.02 is: I think so 👍

**Comment by lee-dohm** [comment]
Thanks @MikeMcQuaid ... I'll see about working on it during downtime in the CampS minisummit this week.

**Comment by bkeepers** [comment]
@lee-dohm and I talked about this a few weeks ago and decided it doesn't really make sense for these to be in the same app.

**Comment by MikeMcQuaid** [comment]
@lee-dohm @bkeepers can these plugins both be used at once without "fighting" i.e. does the no response plugin ignore probot-stale?

**Comment by lee-dohm** [comment]
I'm in the process of rewriting probot-no-response. I'll definitely include
that in my testing. If you've got specific scenarios where you saw them
"fighting", that would be a huge help 🙇

**Comment by MikeMcQuaid** [comment]
@lee-dohm I haven't seen these bots fighting specifically but I've seen Homebrew's probot-no-response equivalent "fight" probot-stale by not figuring that probot-stale's comments count as a response. The test case would be making sure bots ignore each other when figuring out responses/stale status. Give me a shout as I'm interested in using probot-no-response for Homebrew after the rewrite!

**Comment by bkeepers** [comment]
stale ignores bot activity for "unmarking", but it does rely on GitHub's notion of `updated` for issues. So the bot activity won't unmark the issue (thus starting the staleness clock over again), but it will delay closing of the issue.

https://github.com/probot/stale/blob/master/index.js#L21

**Pull request closed without merging**
