### PR TITLE
Probot ~v8~ v9

### PR DESCRIPTION
**Pull request by tcbyrd**
Closes #178 

First pass at getting this updated to start working with newest Probot/Octokit. Currently pulling in scheduler from [probot/scheduler#probot-v8](https://github.com/probot/scheduler/tree/probot-v8). Will update once we publish the npm package.

I'm also going to add some features to make it a little nicer, including support for [YAML validation](https://github.com/probot/stale-action#yaml-validation) and some of the open PRs/issues that add new features.

### CODE REVIEW

**Comment by flaper87** [comment]
o/

I just noticed this PR after submitting a similar (prob not as good) one: https://github.com/probot/stale/pull/218

Can we get one of these in?

Thanks a lot :)

**Comment by acidicX** [comment]
@flaper87 is it possible to get this merged & released? :)

**Comment by flaper87** [comment]
@aidicX I certainly hope so but I'm not the maintainer :( @tcbyrd is

**Comment by acidicX** [comment]
@flaper87 alright, I though since you approved it you might be able to merge it was well.

@tcbyrd is it possible to get this merged & released? :)

**Pull request closed without merging**
