### PR TITLE
Bugfix onlyLabels

### LINKED ISSUE #207: onlyLabels not working
Hi 👋 

I tried to introduce stale bot to comment stale issues which has specific label, but stale bot has marked all issues. Can you take a look and let me know if something is not configured correctly? 

Here is test repository.
https://github.com/takose/stalebot-test

stale.yml
```yml
# Configuration for probot-stale - https://github.com/probot/stale

# Number of days of inactivity before an Issue or Pull Request becomes stale
daysUntilStale: 1

# Issues or Pull Requests with these labels will never be considered stale. Set to `[]` to disable
exemptLabels: []

# Only issues or pull requests with all of these labels are check if stale. Defaults to `[]` (disabled)
onlyLabels:
  - TestLavbel

# Number of days of inactivity before an Issue or Pull Request with the stale label is closed.
# Set to false to disable. If disabled, issues still need to be closed manually, but will remain marked as stale.
daysUntilClose: false

# Label to use when marking as stale
staleLabel: wontfix

# Comment to post when marking as stale. Set to `false` to disable
markComment: >
  Please check progress.
```

Thanks.

### PR DESCRIPTION
**Pull request by takose**
To Fix #207 

> I tried to introduce stale bot to comment stale issues which has specific label, but stale bot has marked all issues. 

I just fixed this! I hope this PR will be merged !! 😘

### CODE REVIEW

**Comment by skjnldsv** [comment]
cc @tcbyrd @JasonEtco @bkeepers

**Comment by takose** [comment]
@tcbyrd can you see this ? 👀

**Comment by tcbyrd** [comment]
Hey, @takose yes I see it. Sorry have been out of the country for a bit and not able to focus on Probot. Will hopefully have some time to focus on this later in the week. Thanks for your patience!

**Comment by takose** [comment]
Hi @tcbyrd !
have you busy yet..? I'm looking forward to being reviewed this PR 😖

**Comment by utakayuki** [comment]
Hi @tcbyrd! 
Any updates on this issue??

**Comment by aeneasr** [comment]
I think this can be merged easily, seems like a straight forward fix for an annoying issue :)

**Comment by dfawley** [comment]
If this fix looks right, please merge and deploy.  This just hit https://github.com/grpc/grpc-go when we enabled the stale bot.

**Comment by blacelle** [comment]
Hi @tcbyrd!
Any updates on this issue??

**Comment by blacelle** [comment]
@JasonEtco Thanks a lot. How long would it take for installed stale probot to take advantage of this merged PR? (I guess you need to issue a new release of the Github App)

**Comment by JasonEtco** [comment]
Already deployed 🙂

**Pull request merged**
